name: Build Project

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  # Build App
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.403
      - name: Build Solution
        run: |
          nuget restore
          msbuild ./Climber.Forms.sln /verbosity:normal /t:Rebuild /p:Configuration=Release